package com.svm.hackathon.model;
// Generated Apr 26, 2016 11:43:22 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.svm.hackathon.framework.GenericManyToManyEntity;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * UserSkill generated by hbm2java
 */
@Entity
@Table(name = "user_skill", catalog="ebdb")
public class UserSkill implements java.io.Serializable, GenericManyToManyEntity<User, Skill> {

	private Integer id;
	private Date timestamp;
	private Skill skill;
	private User user;

	public UserSkill() {
	}

	public UserSkill(Skill skill, User user) {
		this.skill = skill;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "timestamp", nullable = false, length = 19, columnDefinition="DATETIME DEFAULT CURRENT_TIMESTAMP")
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@JsonBackReference(value = "user-skill-skill")
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "skillid", nullable = false)
	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	@JsonBackReference(value = "user-skill-user")
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public void sleftEntity(User t) {
		// TODO Auto-generated method stub
		this.user = t;
	}

	@Override
	public void srightEntity(Skill t) {
		// TODO Auto-generated method stub
		this.skill = t;
	}

	@Override
	public User gleftEntity() {
		// TODO Auto-generated method stub
		return this.user;
	}

	@Override
	public Skill grightEntity() {
		// TODO Auto-generated method stub
		return this.skill;
	}

}
