package com.svm.hackathon.model;
// Generated Apr 26, 2016 11:43:22 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.svm.hackathon.framework.GenericEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog="ebdb")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class User implements java.io.Serializable, GenericEntity {

	private Integer id;
	private String firstname;
	private String lastname;
	private String address1;
	private String address2;
	private String email;
	private String title;
	private String experience;
	private String icon;
	private String username;
	private String phone;
	private Double lat;
	private Double lng;
	private Set<UserOffice> userOffices = new HashSet<UserOffice>(0);
	private Set<UserSkill> userSkills = new HashSet<UserSkill>(0);

	public User() {
	}

	public User(String email, String username) {
		this.email = email;
		this.username = username;
	}

	public User(String firstname, String lastname, String address1, String address2, String email, String title,
			String experience, String icon, String username, Set<UserOffice> userOffices, Set<UserSkill> userSkills) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.address1 = address1;
		this.address2 = address2;
		this.email = email;
		this.title = title;
		this.experience = experience;
		this.icon = icon;
		this.username = username;
		this.userOffices = userOffices;
		this.userSkills = userSkills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname", length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "address1", length = 45)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 45)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "email", nullable = true, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "experience", length = 45)
	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	@Column(name = "icon", length = 45)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "username", nullable = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "lat")
	public Double getLat() {
		return lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	@Column(name = "lng")
	public Double getLng() {
		return lng;
	}

	public void setLng(Double lng) {
		this.lng = lng;
	}

	@JsonManagedReference(value = "user-office-user")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserOffice> getUserOffices() {
		return this.userOffices;
	}

	public void setUserOffices(Set<UserOffice> userOffices) {
		this.userOffices = userOffices;
	}

	//cascadeTypeALL should attach entities
	@JsonManagedReference(value = "user-skill-user")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserSkill> getUserSkills() {
		return this.userSkills;
	}

	public void setUserSkills(Set<UserSkill> userSkills) {
		this.userSkills = userSkills;
	}
	
	@Column(name = "phone")
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
