package com.svm.hackathon.model;
// Generated Apr 26, 2016 11:43:22 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.svm.hackathon.framework.GenericManyToManyEntity;
import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * UserOffice generated by hbm2java
 */
@Entity
@Table(name = "user_office", catalog="ebdb")
public class UserOffice implements java.io.Serializable, GenericManyToManyEntity<User, Office> {

	private Integer id;
	private Office office;
	private User user;

	public UserOffice() {
	}

	public UserOffice(Office office, User user) {
		this.office = office;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonBackReference(value = "user-office-office")
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "officeid", nullable = false)
	public Office getOffice() {
		return this.office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}

	@JsonBackReference(value = "user-office-user")
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public void sleftEntity(User t) {
		// TODO Auto-generated method stub
		this.user = t;
	}

	@Override
	public void srightEntity(Office t) {
		// TODO Auto-generated method stub
		this.office = t;
	}

	@Override
	public User gleftEntity() {
		// TODO Auto-generated method stub
		return this.user;
	}

	@Override
	public Office grightEntity() {
		// TODO Auto-generated method stub
		return this.office;
	}

}
